### ISSUE TITLE
Stop sizing circles based on time since login

### ISSUE THREAD

**Issue by rutmanz** [flamingchickens1540/CLUCK#11]
Could be replaced with 
- Total hours for the day
- Random sizes
- Identically sized bubbles

**Comment by Brelee2222** [comment]
Using total hours of the day might make things worse.

Randomizing the sizes would mean we would have to clamp their values to prevent them from getting too large or too small, but if the problem is about discouraging people from logging out, *maybe we should make them be responsible* or we can clamp the sizes so that there's a consistency in size and it solves the problem.

**Comment by forbeskcg** [comment]
I'd agree, I don't think adjusting size based on how long you're logged in is proving to be a good idea generally. Random sizes might encourage people to repeatedly log in/out until they receive a large bubble. We probably don't want to go down the peer-policing rabbit hole, and everyone is otherwise using the system properly. I would rather just not have differently sized bubbles!

**Comment by Brelee2222** [comment]
I kind of like the different sized bubbles because it makes the dashboard look cool. I'm fine if we have same size circles, but I think for now, I am going to fight for different size circles. Anyways, if we do it by random size, we can try making something that randomizes size for everyone each day. 

If we apply a psychology to this, We can try making the circles look smaller compared to each other but not have a large difference in size.  For example, the smallest group of bubbles will have the same size, the second smallest sizes will be the average size of the smallest and the second smallest, the third will be the average of the first, second and third, etc.

**Comment by rutmanz** [comment]
> Using total hours of the day might make things worse.

Using the day's total hours would get rid of the motivation to stay logged in to avoid resetting your size. It would keep the different bubble sizes, which look cooler than uniform sizes, but would remove the possibility of shenanigans. People wouldn't keep signing in and out to get a new size, people wouldn't be hesitant to sign out for short durations because it wouldn't care how long their most recent sign in is, but people would have a size that actually meant something.

**Comment by Brelee2222** [comment]
That actually encourages people to wake up at 11:30pm to break into the outback to login early so they can assert dominance on the dashboard. Maybe we can do that, but make it hourly. And for an understanding of what I mean from averaging, it would work by averaging bubbles smaller than it with it to decrease its size. 

size | new Size
1 - 1
2 - 1.5
3 - 1.83
4 - 2.08

**Comment by forbeskcg** [comment]
If we were to keep the different sizes, I'd agree that the range is too high right now. @Brelee2222 's 2:1 ratio suggestion for largest/smallest sounds reasonable. Using the total hours for the day is also a fine compromise. I just hope I don't have to set up a security camera 😬

**Comment by Brelee2222** [comment]
Ok. Im gonna push it with circle packer 2.0. If it gets to setting up a securtiy cam, dont let zach set it up. He lives in the lab.

**Comment by azaleacolburn** [comment]
> If we were to keep the different sizes, I'd agree that the range is too high right now. @Brelee2222 's 2:1 ratio suggestion for largest/smallest sounds reasonable. Using the total hours for the day is also a fine compromise. I just hope I don't have to set up a security camera 😬

Ya, the max ratio should definitely be 2:1

**Comment by Brelee2222** [comment]
The ratio is dependent on the memberDiv size

**Comment by Brelee2222** [comment]
@Ewie21 At this point, I think circle packer is done, but it probably need tweaking of the values
